server:
  port: 8087

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/Doit
    username: root
    password: 8338


  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: true

